name: lavahands 
main: com.paulhroth.LavaHandsPlugin
version: ${version}
author: paulhroth
commands:
  LavaHands:
    description: Turns blocks you touch into lava at the expense of your food level.
    aliases: [lavahands, lavaHands, Lavahands]
